language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update --quiet
  - sudo apt-get install --yes build-essential
  - sudo apt-get install --yes ant python
  - export DEBIAN_FRONTEND=noninteractive
  - export THIRDPARTY_DIR=${PWD}/3rdparty
  - export GOOGLETEST_DIR=${THIRDPARTY_DIR}/googletest-master
  - export GTEST_DIR=${GOOGLETEST_DIR}/googletest
  - export GMOCK_DIR=${GOOGLETEST_DIR}/googlemock

script:
  - clang --version
  - gcc --version
  - ant -version
  - python --version

script:
  - cp bak/BAK ${GOOGLETEST_DIR}/BUCK
  - buck build //3rdparty/googletest-master:gtest

script:
  - buck targets
  - buck build //:mainy --verbose 1 --no-cache
  - buck run //:mainy x y z --no-cache
  - buck test //:greety_test --verbose 1 --num-threads 1 --no-cache
