sudo: required

services:
  - docker

language: cpp

compiler:
  - clang
  - gcc

notifications:
  email:
    on_success: never # default: change
    on_failure: change # default: always

before_install:
  - git submodule update --init
  - docker pull praqma/native-buck:latest
  # - export THIRDPARTY_DIR=${PWD}/3rdparty
  # - export GOOGLETEST_DIR=${THIRDPARTY_DIR}/googletest-master
  # - cp -v ${THIRDPARTY_DIR}/googletest_BUCK ${GOOGLETEST_DIR}/BUCK

script:
  - ls -al ${PWD}
  - docker run --rm --workdir=/workspace --volume ${PWD}:/workspace praqma/native-buck:latest ./build.sh
  - docker run --rm --workdir=/workspace --volume ${PWD}:/workspace praqma/native-buck:latest ./test.sh