language: cpp
dist: trusty
sudo: false
compiler:
  - clang
  - gcc
install:
  - export CXX="g++-5"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test  # newer gcc than precise supported.
    packages:
      - g++-5
notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always

before_install:
  - sudo apt-get update --quiet
  - sudo apt-get install --yes build-essential
  - sudo apt-get install --yes ant python
  - export DEBIAN_FRONTEND=noninteractive
  - export THIRDPARTY_DIR=${PWD}/3rdparty
  - export GOOGLETEST_DIR=${THIRDPARTY_DIR}/googletest-master
  - export GTEST_DIR=${GOOGLETEST_DIR}/googletest
  - export GMOCK_DIR=${GOOGLETEST_DIR}/googlemock
  - export BUCK_DIR=${PWD}/buck-master
  - export CXX="g++-5"

script:
  - clang --version
  - gcc --version
  - ant -version
  - python --version
  -
  - cd ${BUCK_DIR}
  - time ant
  - sudo ln -s ${BUCK_DIR}/bin/buck /usr/local/bin/buck
  - sudo ln -s ${BUCK_DIR}/bin/buckd /usr/local/bin/buckd
  - buck --version
  # - echo "That said, as a sanity check, Buck is capable of building itself. Once you build Buck using Ant, you can re-build Buck using Buck by running ./bin/buck build buck."
  # - echo "https://buckbuild.com/concept/faq.html"
  # - buck targets
  # - time buck build //programs:buck //programs:buckd --verbose 1 --no-cache
  # - buck --version
  - cd -
  -
  - cp bak/BAK ${GOOGLETEST_DIR}/BUCK
  - buck build //3rdparty/googletest-master:gtest
  -
  # - buck targets
  - buck build //:mainy --verbose 1 --no-cache
  - buck run //:mainy x y z --no-cache
  -
  - buck test //:greety_test --verbose 1 --num-threads 1 --no-cache
